apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acc-a.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: acc
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}
        app: acc
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /a?dv=200&t=5
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
